name: "Build"
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: magthe-dev
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build the shell
        env:
          TMPDIR: ${{ github.workspace }}/nix-tmp
        run: |
          mkdir ${TMPDIR}
          nix --accept-flake-config develop --profile dev-profile -c true
          cachix push magthe-dev dev-profile
